spring:
  datasource:
    driver-class-name: com.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/jctfs
    username: jctfs
    password: jctfs

  redis:
    host: localhost
    port: 6379

mybatis:
  configuration:
    map-underscore-to-camel-case: true
